In [1]:
import pandas as pd
import os

In [2]:
# read the book_ratings.csv file
file_path = "/Users/avikumart/Documents/GitHub/Book-recommendation-system/data/book_ratings.csv"
book_ratings = pd.read_csv(file_path)

In [3]:
book_ratings.head()

,isbn,book_title,book_author,publisher,user_id,book_rating
0,0002005018,Clara Callan,Richard Bruce Wright,HarperFlamingo Canada,8,5
1,0002005018,Clara Callan,Richard Bruce Wright,HarperFlamingo Canada,11400,0
2,0002005018,Clara Callan,Richard Bruce Wright,HarperFlamingo Canada,11676,8
3,0002005018,Clara Callan,Richard Bruce Wright,HarperFlamingo Canada,41385,0
4,0002005018,Clara Callan,Richard Bruce Wright,HarperFlamingo Canada,67544,8

In [4]:
book_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885487 entries, 0 to 885486
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   isbn         885487 non-null  object
 1   book_title   885487 non-null  object
 2   book_author  885487 non-null  object
 3   publisher    885487 non-null  object
 4   user_id      885487 non-null  int64
 5   book_rating  885487 non-null  int64
dtypes: int64(2), object(4)
memory usage: 40.5+ MB

In [5]:
# sample the radome 100k rows from the book_ratings dataframe
sampled_book_ratings = book_ratings.sample(n=10000, random_state=42)
sampled_book_ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 414504 to 58552
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   isbn         10000 non-null  object
 1   book_title   10000 non-null  object
 2   book_author  10000 non-null  object
 3   publisher    10000 non-null  object
 4   user_id      10000 non-null  int64
 5   book_rating  10000 non-null  int64
dtypes: int64(2), object(4)
memory usage: 546.9+ KB

In [11]:
# save the sampled_book_ratings dataframe to a csv file
output_file_path = "/Users/avikumart/Documents/GitHub/Book-recommendation-system/data/sampled_book_ratings.csv"
sampled_book_ratings.to_csv(output_file_path, index=False)

In [7]:
user_item_matrix = sampled_book_ratings.pivot_table(index='user_id', columns='isbn', values='book_rating').fillna(0)

In [8]:
user_item_matrix

isbn,0002116286,0002251485,0002255006,000255478X,0004125576,0006174817,0006377157,0006480608,0006497993,0006514480,...,9501517985,950511673X,968150108X,9722002171,9727110800,9838120200,9879402219,B00005U7YK,B0000AA9JB,B0000C7BNG
user_id,,,,,,,,,,,,,,,,,,,,,
75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
372,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278535,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278582,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# save the user_item_matrix to a csv file
output_file_path = "/Users/avikumart/Documents/GitHub/Book-recommendation-system/data/user_item_matrix.csv"
user_item_matrix.to_csv(output_file_path, index=True)

In [10]:
user_item_matrix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5245 entries, 75 to 278637
Columns: 8262 entries, 0002116286 to B0000C7BNG
dtypes: float64(8262)
memory usage: 330.7 MB

In [8]:
# book author matrix
book_author_matrix = sampled_book_ratings.pivot_table(index='user_id', columns='book_author', values='book_rating').fillna(0)

In [8]:
#  create new nw matrix of small dataset and save as a json
sampled_br = book_ratings.sample(n=10000, random_state=42)
sampled_br.info()
sampled_br.to_json("/Users/avikumart/Documents/GitHub/Book-recommendation-system/data/sampled_book_ratings.json", orient='records', lines=True)

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 414504 to 58552
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   isbn         10000 non-null  object
 1   book_title   10000 non-null  object
 2   book_author  10000 non-null  object
 3   publisher    10000 non-null  object
 4   user_id      10000 non-null  int64
 5   book_rating  10000 non-null  int64
dtypes: int64(2), object(4)
memory usage: 546.9+ KB

In [9]:
# load the json file and convert it to a dataframe
sampled_br_df = pd.read_json("/Users/avikumart/Documents/GitHub/Book-recommendation-system/data/sampled_book_ratings.json", orient='records', lines=True)
sampled_br_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   isbn         10000 non-null  object
 1   book_title   10000 non-null  object
 2   book_author  10000 non-null  object
 3   publisher    10000 non-null  object
 4   user_id      10000 non-null  int64
 5   book_rating  10000 non-null  int64
dtypes: int64(2), object(4)
memory usage: 468.9+ KB

In [11]:
pivot = sampled_br_df.pivot_table(index='user_id', columns='isbn', values='book_rating').fillna(0)
pivot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5245 entries, 75 to 278637
Columns: 8262 entries, 0002116286 to B0000C7BNG
dtypes: float64(8262)
memory usage: 330.7 MB

In [13]:
pivot.head()

isbn,0002116286,0002251485,0002255006,000255478X,0004125576,0006174817,0006377157,0006480608,0006497993,0006514480,...,9501517985,950511673X,968150108X,9722002171,9727110800,9838120200,9879402219,B00005U7YK,B0000AA9JB,B0000C7BNG
user_id,,,,,,,,,,,,,,,,,,,,,
75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
372,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
isbn = "0002005018"  # example ISBN
int_isbn = int(isbn)

In [13]:
int_isbn

2005018